apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: paulabloescherswdlab 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: paulabloescherswdlab 
    spec:
      containers:
        - name: paulabloescherswdlab 
          image: containerregistrypa.azurecr.io/paulabloescherswdlab
          ports:
          - containerPort: 8080